Implement Auth
ctc-uci/patriots-and-paws-backend pull request #18
Opened 2022-11-17 06:03 UTC by ctc-devops

Authors:
 ### What does this PR contain?
 ### How did you test these changes?
 ### Attach images (if applicable)
 Closes #11

2022-11-28 04:19 UTC, hang-m-cao requested changes
Looking good! Just some syntactical and best practices changes, but some things I commented on would be addressed once we merge [this issue](https://github.com/ctc-uci/patriots-and-paws-backend/issues/5) which actually creates the user table and routes. So for now, understand the comments I made and be ready to add the authentication-specific changes to the routes. We'll notify you when that's done!

2022-11-28 04:19 UTC, hang-m-cao commented on routes/users.js
> +};
This function exists in the `commons` folder so let's import and use that.

2022-11-28 04:19 UTC, hang-m-cao commented on routes/users.js
> +userRouter.post('/create', async (req, res) => {
Nit-pick: you don't need the `/create` as a `POST` request implies you are creating a new user.

2022-11-28 04:19 UTC, hang-m-cao commented on routes/users.js
> +userRouter.put('/update/:userId', async (req, res) => {
Same comment as with the route for the `POST` request: `/update` is not necessary since that's what a `PUT` request does.

2022-11-28 04:19 UTC, hang-m-cao commented on routes/users.js
> +    });
To keep it consistent with how data is received on the frontend (ie. this implementation requires us to know that data is sent as `accounts` for just the user route), we can pass `users` as is and through `keysToCamel` in `utils.js`.

Let's also send a status code by calling `.status(200)`.

2022-11-28 04:19 UTC, hang-m-cao commented on routes/users.js
> +    });
Note: this should already be implemented in this [issue](https://github.com/ctc-uci/patriots-and-paws-backend/issues/5) which will probably get merged first, so I just wanted to explain the reason for that implementation.

2022-11-28 04:19 UTC, hang-m-cao commented on routes/users.js
> +    });
In addition to the comment above (re: the returned data for the `GET /` route), we're also going to have everything sent back as an array even if it's one object. On the frontend, we'll just extract that manually.

2022-11-28 04:19 UTC, hang-m-cao commented on routes/users.js
> +    res.status(400).send(err.message);
Nit-pick: the status code here should be 500 to signify an internal error whereas 400 is invalid input (more on that [here](https://enterprisecraftsmanship.com/posts/rest-api-response-codes-400-vs-500/#:~:text=The%20main%20difference%20between%20the,itself%20who%20caused%20the%20problem.)).

2022-11-28 04:19 UTC, hang-m-cao commented on routes/users.js
> +    );
Because we are using the `db` object, we can use named parameters instead of ordered parameters (ie. the arguments are matched based on the order in the given array). See [this query](https://github.com/ctc-uci/patriots-and-paws-backend/pull/14/files#diff-fc074c6d7465bef95caefa94a2b0a18d5810e2204cc399dc4dd9d7a646b13affR15-R16) with the preferred syntax.

2022-12-04 10:15 UTC, hang-m-cao requested changes
You should be good to go after these changes (and after PR #14 gets merged into your branch to address any conflicts) to the SQL statement for POST/DELETE and some more code clean up for the data being returned.

2022-12-04 10:15 UTC, hang-m-cao commented on routes/users.js
> +    res.status(200).json(keysToCamel(user) ?? []);
We don't need the `?? []` check. the `db` object will return an empty array if there is nothing.

2022-12-04 10:15 UTC, hang-m-cao commented on routes/users.js
> +    res.status(400).send(err.message);
Nit-pick: status code should be 500.

2022-12-04 10:15 UTC, hang-m-cao commented on routes/users.js
> +    res.status(400).send(err.message);
Nit-pick: status code should be 500.

2022-12-04 10:15 UTC, hang-m-cao commented on routes/users.js
> +    res.status(400).send(err.message);
Nit-pick: status code should be 500.

2022-12-04 10:15 UTC, hang-m-cao commented on routes/users.js
> +    res.status(200).json(keysToCamel(user) ?? []);
Unnecessary check.

2022-12-04 10:15 UTC, hang-m-cao commented on routes/users.js
> +      'UPDATE users SET first_name = $(firstName), last_name = $(lastName), phone_number = $(phoneNumber), email = $(email) WHERE id = $(id) RETURNING *',
The `PUT` request should account for optional parameters (ie. not requiring all values to be passed to update the information). Since the other PR has [the change](https://github.com/ctc-uci/patriots-and-paws-backend/blob/8d6a30c4d67de82791f328eacb9aa7f603508b42/routes/users.js#L43-L62) needed here, you can wait until that's merge and then resolve the conflict so you don't have to make any unnecessary changes trying to replicate that file.

2022-12-04 10:15 UTC, hang-m-cao commented on routes/users.js
> +    res.status(200).json(keysToCamel(newUser) ?? []);
Unnecessary check.

2022-12-04 10:15 UTC, hang-m-cao commented on routes/users.js
> +    isAlphaNumeric(id); // ID must be alphanumeric
Remember to pass in an error message to throw if `id` is not alphanumeric. See the function for how it's being used. It can be something simple.

2022-12-04 10:15 UTC, hang-m-cao commented on routes/users.js
> +    isAlphaNumeric(id); // ID must be alphanumeric
Pass in error message.

2022-12-04 10:15 UTC, hang-m-cao commented on routes/users.js
> +    isAlphaNumeric(id); // ID must be alphanumeric
Pass in error message.

2022-12-04 10:15 UTC, hang-m-cao commented on routes/users.js
> +    res.status(200).send(`Deleted user with ID: ${id}`);
In the case we need the user data, let's retrieve that data in the SQL and return it in the response body.

2022-12-09 05:04 UTC, ctc-devops commented on firebase.js
> +const credentials = require('./firebase-adminsdk.json');
🚫 **[eslint]** <[import/no-unresolved](https://github.com/import-js/eslint-plugin-import/blob/v2.26.0/docs/rules/no-unresolved.md)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unable to resolve path to module './firebase-adminsdk.json'.

2022-12-12 10:28 UTC, hang-m-cao approved these changes
Looks good! great job :)

2022-12-12 10:29 UTC, merged