Set up foreign keys and updated tables in database
ctc-uci/patriots-and-paws-backend pull request #23
Opened 2023-01-18 00:15 UTC by ctc-devops

Authors:
 ### What does this PR contain?
 ### How did you test these changes?
 ### Attach images (if applicable)
 Closes #13

2023-01-22 09:12 UTC, jrock-3 requested changes
a few notes to clean up the rest of the code, otherwise this looks amazing! thanks for all your hard work :D

2023-01-22 09:12 UTC, jrock-3 commented on routes/donations.js
> +    // console.log(donation);
delete any `console.log` messages even if they are commented out, there's a few more throughout this pr

2023-01-22 09:12 UTC, jrock-3 commented on routes/donations.js
> +      submittedDate,
`submittedDate` isn't an attribute passed from the frontend, it should be automatically generated using [JS Date Objects](https://www.freecodecamp.org/news/javascript-get-current-date-todays-date-in-js/)

2023-01-22 09:12 UTC, jrock-3 commented on routes/donations.js
> +        ${submittedDate ? 'last_edited_date, ' : ''}
the figma database model was incorrect, we just changed it so `submittedDate` and `lastEditedDate` aren't optional parameters

2023-01-22 09:12 UTC, jrock-3 commented on routes/donations.js
> +    });
it's more proper to use a `forEach` loop instead of `map` since you're not actually using the return value of `insertPicture` or `insertFurniture`

2023-01-22 09:12 UTC, jrock-3 commented on routes/donations.js
> +    });
follow the same naming scheme as shown in `insertPictures` and the database model for argument names

2023-01-22 09:12 UTC, jrock-3 commented on routes/donations.js
> +      submittedDate,
`submittedDate` won't be an argument passed into this route, you can go ahead and delete it

2023-01-22 09:12 UTC, jrock-3 commented on routes/furniture.js
>        },
you can reuse the helper function you wrote in `furnitureUtils` here

2023-01-22 09:12 UTC, jrock-3 commented on routes/pictures.js
>      );
you can reuse the helper function you wrote in `pictureUtils` instead

2023-01-22 09:12 UTC, jrock-3 commented on routes/furniture.js
>              name = $(name)
for `put` routes all parameters should be optional, also do an edge case check if nothing is passed in

2023-01-22 09:12 UTC, jrock-3 commented on routes/pictures.js
>        },
for `put` routes all parameters should be optional, also do an edge case check if nothing is passed in

2023-01-29 11:20 UTC, hang-m-cao submitted a review, later dismissed
thanks for making the changes! just additional comments to fix the structure of the database tables and optimize some queries :)

2023-01-29 11:20 UTC, hang-m-cao commented on routes/donations.js
>  const express = require('express');
We need to add a new constraint to the `donations` table so that no two donations can have the same route ID and order, which can be done like [this](https://stackoverflow.com/questions/14221775/in-postgresql-force-unique-on-combination-of-two-columns).

2023-01-29 11:20 UTC, hang-m-cao commented on routes/donations.js
> +    });
Better yet, this can be done in one insert call by unnesting the arrays like [this](https://stackoverflow.com/questions/20815028/how-do-i-insert-multiple-values-into-a-postgres-table-at-once). Here is more on the [unnest function](https://hevodata.com/learn/postgresql-unnest/) (you can scroll to find where it shows unnesting multiple). One insert statement is typically faster.

2023-01-29 11:20 UTC, hang-m-cao commented on routes/donations.js
>      } = req.body;
On further thought of when/how donations are created, we can set the default values for `routeId`, `orderNum`, and `status`. `routeId` and `orderNum` can be `null` as they will never have a route associated until they are approved which takes manual effort. `status` can default to `pending` for a similar reason.

2023-01-29 11:20 UTC, hang-m-cao commented on routes/donations.js
> +    });
See comment above about making the insert process one statement.

2023-01-29 11:20 UTC, hang-m-cao commented on routes/pictures.js
> +        ${donationId ? 'donation_id = $(donationId), ' : ''}
Logically, you should not be able to change the donation that a picture is associated with.

2023-01-29 11:20 UTC, hang-m-cao commented on routes/routes.js
> +    const donationRes = await db.query(`SELECT * FROM donations WHERE routeId = $(routeId);`, {
`routeId` should be `route_id`.

2023-01-29 11:20 UTC, hang-m-cao commented on routes/routes.js
> +    routeInfo[0].pictures = donationRes;
`pictures` attribute should be `donations`.

2023-01-29 11:20 UTC, hang-m-cao commented on routes/routes.js
> +      `INSERT INTO routes (${driverId ? 'driver_id, ' : ''} id)
There should be a way to create a new route (with a newly generated id) that already has donations related to it (donation data in passed in the payload).

2023-01-29 11:20 UTC, hang-m-cao commented on server/schema/routes.sql
> +  driver_id VARCHAR(256) REFERENCES users(id) ON DELETE CASCADE
If a driver gets deleted, all routes associated with that driver should not be deleted. The exact action is still to be determined, so for now, change the `on delete cascade` to `no action`.

2023-01-29 11:20 UTC, hang-m-cao commented on server/schema/donations.sql
> +   route_id INT REFERENCES routes(id) ON DELETE CASCADE,
If a route gets deleted, all donations associated with that route should not be deleted. The exact action is still to be determined, so for now, change the `on delete cascade` to `no action`.

2023-02-05 05:45 UTC, hang-m-cao commented
Because another task relied on a change in the backend table, we made some edits to the tables.
- the `donations` table to change the `ON DELETE` constraint to `SET NULL` instead.
- two columns were added to the `routes` table: a name and a date (the scheduled date for each donation is now in the corresponding `route_id`).

Please make an additional change to the donations `GET` requests to join the `donations` and `routes` table to retrieve that date if any.

2023-02-05 05:46 UTC, hang-m-cao commented on server/schema/donations.sql
> +   route_id INT REFERENCES routes(id) ON DELETE CASCADE,
This change was made to the database tables already. Code may not have been pushed.

2023-02-10 11:32 UTC, jrock-3 approved these changes
lgtm

2023-02-10 11:40 UTC, merged