Create Manage Donation Form Endpoints
ctc-uci/patriots-and-paws-backend pull request #28
Opened 2023-02-02 04:56 UTC by ctc-devops

Authors:
 ### What does this PR contain?
 ### How did you test these changes?
 ### Attach images (if applicable)
 Closes #24

2023-02-17 04:17 UTC, hang-m-cao approved these changes
Looks great! Good job on the new router :)

2023-02-17 06:11 UTC, hang-m-cao requested changes
After reviewing the frontend, let's change the `POST` request to make it more efficient for our use case. Can you also add the furniture count to the `GET /donations` request?

2023-02-17 06:11 UTC, hang-m-cao commented on routes/furnitureOptions.js
> +});
Let's change this `POST` request to take in a list of items to insert, and add them all at once.

2023-02-17 06:11 UTC, hang-m-cao commented on routes/furnitureOptions.js
> +});
Refer to [this code](https://github.com/ctc-uci/patriots-and-paws-backend/blob/dev/routes/donations.js#L155-L168) in donation `PUT` request as an example. Essentially, you would want to split the array of objects into two arrays: `name` and `acceptedStatus`. Then, in the `unnest` function in the SQL statement, pass the two arrays and update the variable accordingly.

2023-02-17 06:19 UTC, hang-m-cao commented on routes/furnitureOptions.js
> +router.get('/', async (req, res) => {
Nit-pick: can we make this name a bit more verbose like `furnitureOptionsRouter`?

2023-02-22 05:06 UTC, ctc-devops commented on routes/furnitureOptions.js
> +    console.log(deleted);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2023-03-05 22:38 UTC, NwinNwin submitted a review, later dismissed

2023-03-05 22:58 UTC, ctc-devops commented on routes/furniture.js
> +        count,
🚫 **[eslint]** <[no-dupe-keys](https://eslint.org/docs/rules/no-dupe-keys)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Duplicate key 'count'.

2023-03-05 23:08 UTC, NwinNwin approved these changes

2023-03-05 23:09 UTC, hang-m-cao approved these changes

2023-03-05 23:13 UTC, merged