Create Donor Dashboard Endpoints
ctc-uci/patriots-and-paws-backend pull request #29
Opened 2023-02-07 07:31 UTC by ctc-devops

Authors:
 ### What does this PR contain?
 ### How did you test these changes?
 ### Attach images (if applicable)
 Closes #25

2023-02-14 04:34 UTC, jrock-3 requested changes
Great work, I have some changes to make, which include refactoring `/donation/verify`. Almost there!

2023-02-14 04:34 UTC, jrock-3 commented on routes/donations.js
> +    const id = nanoid();
changing to 6 digit alphanumeric id (refer to [docs](https://github.com/ai/nanoid#custom-alphabet-or-size))

2023-02-14 04:34 UTC, jrock-3 commented on routes/donations.js
> +  if (donation[0].email === email) {
protect against queries that return empty arrays, use either optional chaining or another bool check

2023-02-14 04:34 UTC, jrock-3 commented on routes/donations.js
> +    res.status(500).send('donation id and email do not match');
change this to follow the standard backend route format
```
(req, res) => {
  try {

  } catch (err) {
    ...
  }
}
```

2023-02-14 04:34 UTC, jrock-3 commented on routes/donations.js
> +    res.status(500).send('donation id and email do not match');
instead of using statuses to determine whether or not the email/donationId combination is correct, just send a boolean value

2023-02-14 04:34 UTC, jrock-3 commented on routes/donations.js
> +router.get('/verify', async (req, res) => {
in `get` requests, the protocol doesn't allow to pass in a payload (`req.body`), so instead convert this to a `post` route (don't forget to change this in the frontend as well)

2023-02-14 04:34 UTC, jrock-3 commented on server/schema/donations.sql
> +   id PRIMARY KEY,
because we're changing the id to be a 6 digit alphanumeric string, change this to a `varchar(6)` and update it in _pgadmin_ as well.

2023-02-20 10:54 UTC, jrock-3 approved these changes, later dismissed
Great work! Looks good to me 👍

2023-02-23 01:34 UTC, ctc-devops commented on routes/donations.js
> +        ${routeId ? '$(routeId), ' : ''}
🚫 **[eslint]** <[no-undef](https://eslint.org/docs/rules/no-undef)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'routeId' is not defined.

2023-02-23 01:34 UTC, ctc-devops commented on routes/donations.js
> +        ${orderNum ? '$(orderNum), ' : ''}
🚫 **[eslint]** <[no-undef](https://eslint.org/docs/rules/no-undef)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'orderNum' is not defined.

2023-02-23 01:34 UTC, ctc-devops commented on routes/donations.js
> +        routeId,
🚫 **[eslint]** <[no-undef](https://eslint.org/docs/rules/no-undef)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'routeId' is not defined.

2023-02-23 01:34 UTC, ctc-devops commented on routes/donations.js
> +        orderNum,
🚫 **[eslint]** <[no-undef](https://eslint.org/docs/rules/no-undef)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'orderNum' is not defined.

2023-02-23 01:38 UTC, merged